name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: financeira
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d financeira"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Dar permissão ao Maven Wrapper
        working-directory: Financeira
        run: chmod +x mvnw

      - name: Build e testes
        working-directory: Financeira
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/financeira
          SPRING_DATASOURCE_DB: financeira
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
        run: ./mvnw clean verify