name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_URL: jdbc:postgresql://postgres:5432/financeira
          POSTGRES_DB: financeira
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Dar permissão ao Maven Wrapper
        working-directory: Financeira
        run: chmod +x mvnw

      - name: Build e testes
        working-directory: Financeira
        run: ./mvnw clean verify